### PR TITLE
Fix Home Assistant error about UNIT_PERCENTAGE

### LINKED ISSUE #11: cannot import name 'UNIT_PERCENTAGE'
## Version of the custom_component
VERSION = "2.0.1"
## Configuration

foldingathomecontrol:
  - address: "192.168.1.130"
    port: 36330
    #password: "password"

Add your logs here.

`Sep 19 09:25:26 ultra hass[734]: 2020-09-19 09:25:26 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: foldingathomecontrol - cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/const.py)`

## Describe the bug
The HACS integration throws this error on start up.  Just doing some digging I can up with: UNIT_PERCENTAGE was changed to PERCENTAGE in 0.115. The integration needs to update their code. Please open a github issue on the integration’s repo

```

### PR DESCRIPTION
**Pull request by sqldiablo**
Fixes #11 

Home Assistant changed UNIT_PERCENTAGE to just PERCENTAGE. This change is to reflect that.

### CODE REVIEW

**Comment by eifinger** [comment]
Thank you for your PR!
Can you please wrap the import in a try except so this integration continues to work with versions <0.115?

**Comment by sqldiablo** [comment]
@eifinger, I came up with a slightly different approach. I'm checking the major and minor version number for HASS, and using the correct const based on that. Please let me know if that works for you instead of the try/except.

**Comment by sqldiablo** [comment]
I'm not sure why this test failed. I'm testing it locally, and it's working fine for me.

**Comment by eifinger** [comment]
Thank you!
